# ============================================================
# VERIDIAN CORP - AIONOS ASSIGNMENT 2 DATA PACK
# ============================================================
# Source:
# Assignment 2 - Internal Service Agent (IT Support)
#
# This file contains:
# 1. Employee Requests REQ-01 to REQ-15
# 2. Existing Ticket Queue TK-1042 to TK-1051
#
# IMPORTANT:
# These records are supplied assignment data.
# They are NOT generated by the agent.
# ============================================================


# ============================================================
# EMPLOYEE REQUESTS
# ============================================================

EMPLOYEE_REQUESTS = [

    {
        "request_id": "REQ-01",
        "employee": "Aditi Sharma",
        "email": "aditi.sharma@veridian-corp.example",
        "date_opened": "Mon 21 Sep",
        "request": (
            "My laptop won't turn on at all, it's completely dead, "
            "had it about 3.5 years now."
        ),
        "initial_action": "Not started",
    },

    {
        "request_id": "REQ-02",
        "employee": "Vikram Chawla",
        "email": "vikram.chawla@veridian-corp.example",
        "date_opened": "Mon 21 Sep",
        "request": (
            "Can I get Wi-Fi access for a guest visiting our "
            "office tomorrow?"
        ),
        "initial_action": "Not started",
    },

    {
        "request_id": "REQ-03",
        "employee": "Karan Mehta",
        "email": "karan.mehta@veridian-corp.example",
        "date_opened": "Mon 21 Sep",
        "request": (
            "I'm locked out of my account, tried my password 6 times."
        ),
        "initial_action": "In progress — reset queued",
    },

    {
        "request_id": "REQ-04",
        "employee": "Ritu Bhatia",
        "email": "ritu.bhatia@veridian-corp.example",
        "date_opened": "Tue 22 Sep",
        "request": (
            "Need approval to install a data-analysis tool "
            "that's not in the software catalog."
        ),
        "initial_action": "Waiting on Security review",
    },

    {
        "request_id": "REQ-05",
        "employee": "Sanjay Oberoi",
        "email": "sanjay.oberoi@veridian-corp.example",
        "date_opened": "Tue 22 Sep",
        "request": (
            "My VPN stopped working this morning, says "
            "credentials expired."
        ),
        "initial_action": "Not started",
    },

    {
        "request_id": "REQ-06",
        "employee": "Meera Iyer",
        "email": "meera.iyer@veridian-corp.example",
        "date_opened": "Tue 22 Sep",
        "request": (
            'Printer on the 3rd floor keeps showing "paper jam" '
            "even though there's no jam."
        ),
        "initial_action": "Investigating — technician assigned",
    },

    {
        "request_id": "REQ-07",
        "employee": "Farhan Ali",
        "email": "farhan.ali@veridian-corp.example",
        "date_opened": "Wed 23 Sep",
        "request": (
            "I've started working from home 4 days a week, "
            "how do I get a monitor?"
        ),
        "initial_action": "Not started",
    },

    {
        "request_id": "REQ-08",
        "employee": "Ananya Reddy",
        "email": "ananya.reddy@veridian-corp.example",
        "date_opened": "Wed 23 Sep",
        "request": (
            "I think I got a phishing email asking for my login — "
            "forwarding it to a few teammates to check."
        ),
        "initial_action": "Escalated to Security (auto-flagged)",
    },

    {
        "request_id": "REQ-09",
        "employee": "Rohit Desai",
        "email": "rohit.desai@veridian-corp.example",
        "date_opened": "Wed 23 Sep",
        "request": (
            "My mailbox is full and I can't send emails."
        ),
        "initial_action": "Not started",
    },

    {
        "request_id": "REQ-10",
        "employee": "Kavya Pillai",
        "email": "kavya.pillai@veridian-corp.example",
        "date_opened": "Wed 23 Sep",
        "request": (
            "Can someone give me admin access to the finance "
            "reporting server? Need it urgently for month-end."
        ),
        "initial_action": "Not started",
    },

    {
        "request_id": "REQ-11",
        "employee": "Nikhil Bansal",
        "email": "nikhil.bansal@veridian-corp.example",
        "date_opened": "Thu 24 Sep",
        "request": (
            "New contractor joining my team next week, "
            "they'll need VPN access."
        ),
        "initial_action": "Not started",
    },

    {
        "request_id": "REQ-12",
        "employee": "Sneha Kulkarni",
        "email": "sneha.kulkarni@veridian-corp.example",
        "date_opened": "Thu 24 Sep",
        "request": (
            "I can't log into the expense tool, keeps saying "
            "invalid credentials."
        ),
        "initial_action": (
            "Waiting on employee response "
            "(asked for a screenshot, no reply yet)"
        ),
    },

    {
        "request_id": "REQ-13",
        "employee": "Aman Gupta",
        "email": "aman.gupta@veridian-corp.example",
        "date_opened": "Thu 24 Sep",
        "request": (
            "Laptop screen is flickering on and off, had it "
            "2 years, might just need a fix not a replacement."
        ),
        "initial_action": "Not started",
    },

    {
        "request_id": "REQ-14",
        "employee": "Tanya Chopra",
        "email": "tanya.chopra@veridian-corp.example",
        "date_opened": "Fri 25 Sep",
        "request": (
            "Requesting approval to install a browser extension "
            "for productivity tracking."
        ),
        "initial_action": "Not started",
    },

    {
        "request_id": "REQ-15",
        "employee": "Rahul Menon",
        "email": "rahul.menon@veridian-corp.example",
        "date_opened": "Fri 25 Sep",
        "request": "hey can you help, its not working",
        "initial_action": "Not started",
    },
]


# ============================================================
# EXISTING TICKET QUEUE
# ============================================================

EXISTING_TICKETS = [

    {
        "ticket_id": "TK-1042",
        "employee": "R. Verma",
        "issue_summary": "VPN credential expired",
        "status": "Resolved (closed)",
        "is_active": False,
    },

    {
        "ticket_id": "TK-1043",
        "employee": "S. Iyer",
        "issue_summary": "Laptop replacement (3.2 yrs old)",
        "status": "Approved — pending fulfillment (active)",
        "is_active": True,
    },

    {
        "ticket_id": "TK-1044",
        "employee": "A. Khan",
        "issue_summary": "Non-catalog software request",
        "status": "Pending Security review (active)",
        "is_active": True,
    },

    {
        "ticket_id": "TK-1045",
        "employee": "P. Joshi",
        "issue_summary": "Mailbox quota increase",
        "status": "Approved at 35GB (closed)",
        "is_active": False,
    },

    {
        "ticket_id": "TK-1046",
        "employee": "M. Das",
        "issue_summary": "Printer paper jam, floor 2",
        "status": "Resolved (closed)",
        "is_active": False,
    },

    {
        "ticket_id": "TK-1047",
        "employee": "K. Singh",
        "issue_summary": "Home office equipment request",
        "status": "Pending Finance (active)",
        "is_active": True,
    },

    {
        "ticket_id": "TK-1048",
        "employee": "T. Rao",
        "issue_summary": "Phishing email reported",
        "status": (
            "Escalated to Security — under investigation (active)"
        ),
        "is_active": True,
    },

    {
        "ticket_id": "TK-1049",
        "employee": "V. Nambiar",
        "issue_summary": "Password reset",
        "status": "Resolved (closed)",
        "is_active": False,
    },

    {
        "ticket_id": "TK-1050",
        "employee": "J. Fernandes",
        "issue_summary": "Admin access request",
        "status": (
            "Rejected — no business justification provided (closed)"
        ),
        "is_active": False,
    },

    {
        "ticket_id": "TK-1051",
        "employee": "L. Menon",
        "issue_summary": "Guest Wi-Fi issued",
        "status": "Resolved (closed)",
        "is_active": False,
    },
]


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def get_employee_request(request_id):
    """
    Return one employee request using its request ID.
    """

    for request in EMPLOYEE_REQUESTS:
        if request["request_id"] == request_id:
            return request

    return None


def get_active_tickets():
    """
    Return only active tickets from the supplied ticket queue.
    """

    return [
        ticket
        for ticket in EXISTING_TICKETS
        if ticket["is_active"]
    ]


def get_closed_tickets():
    """
    Return historical/closed tickets.
    """

    return [
        ticket
        for ticket in EXISTING_TICKETS
        if not ticket["is_active"]
    ]


def get_ticket(ticket_id):
    """
    Return a supplied ticket using its ticket ID.
    """

    for ticket in EXISTING_TICKETS:
        if ticket["ticket_id"] == ticket_id:
            return ticket

    return None